replicaCount: 1

config:
  appEnv: dev

autoscaling:
  minReplicas: 1
  maxReplicas: 2

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"