name: Docker Publish

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Hent kode
        uses: actions/checkout@v4

      - name: Sett opp Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Logg inn på Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Bygg og push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/task-service:latest
            ${{ vars.DOCKERHUB_USERNAME }}/task-service:${{ github.sha }}